"""Add is_active column to Order table

Revision ID: 1f85b32d5919
Revises: 
Create Date: 2025-12-15 14:54:32.289049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f85b32d5919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_order', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
