"""Add is_active column to sale

Revision ID: 446f23a2b564
Revises: 1f85b32d5919
Create Date: 2025-12-15 16:08:56.070564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446f23a2b564'
down_revision = '1f85b32d5919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ready', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('is_ready')

    # ### end Alembic commands ###
